### ISSUE TITLE
Sliding Issue

### ISSUE THREAD

**Issue by RichAppz** [ole/OBSlider#6]
The slider I am implementing is fine tuning an amount paid by a consumer, but for some reason with OBSlider if you slide to the max amount it jumps back a point - for example I want to pay 40.95 I slide the slider to this and it jumps back to 40.94! Any ideas?

**Comment by ole** [comment]
Hm, I can’t reproduce this. Does this also happen to you in the OBSliderDemo app? If not, are you doing anything differently? What is the `minimumValue` and `maximumValue` of your slider?
