### ISSUE TITLE
Absolute value function 'fabsf' given an argument of type 'double'

### ISSUE THREAD

**Issue by jomnius** [ole/OBSlider#8]
Xcode 6.3 warnings:

OBSlider.m:112:34: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value

OBSlider.m:128:67: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value

Also requesting pod version update, if fixed.

**Comment by ole** [comment]
Done.
