### ISSUE TITLE
Thumb jumping when touching/clicking

### ISSUE THREAD

**Issue by DrummerB** [ole/OBSlider#9]
Hi,

I've noticed an issue with your control.
The thumb image and the value of the slide seem to instantly jump a bit to the left or right, when the thumb is touched. The amount of the jump seems to correlate with the current position of the thumb, i.e. when the thumb is all the way to the left it will jump a bit to the right when touched, when it's on the right side it will jump a bit to the left and in the middle it won't jump at all. 

Here is a video demo: https://www.youtube.com/watch?v=RNT5UazGWQA

**Comment by ole** [comment]
Thanks for the report. I’m inclined to close this issue because the `UISlider` in the demo app behaves in exactly the same way so it doesn’t seem to be related to my code. Can you confirm that?

**Comment by DrummerB** [comment]
Well that's weird. I never noticed this behavior of UISlider. You're right.
